# Generated by Django 4.1.3 on 2022-11-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='asin',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
